# Generated by Django 4.1.2 on 2022-10-17 01:13

from django.db import migrations
from lorem.text import TextLorem
from django.utils import timezone

def populate_db(appreg, ed):
    print("hello")
    Blog = appreg.get_model('blog', 'Blog')
    Comment = appreg.get_model('blog', 'Comment')
    contentList = []
    titleList = []
    authorList = []
    for i in range(4):
        authorList.append("Vladmire #" + str(i))
        lorem = TextLorem(srange=(150, 250))
        lorem2 = TextLorem(srange=(2, 4))
        contentList.append(lorem.sentence())
        titleList.append(lorem2.sentence())

    post1 = Blog(title=titleList[0], author=authorList[0], content=contentList[0], posted=timezone.now())
    post1.save()

    for i in range(4):
        Comment(blog=post1, commenter="Dracula #" + str(i), email=f"spooky{i}@hallow.org", content=TextLorem(srange=(4, 12)).sentence(), posted=timezone.now()).save()

    post2 = Blog(title=titleList[1], author=authorList[1], content=contentList[1], posted=timezone.now())
    post2.save()

    for i in range(4):
        Comment(blog=post2, commenter="Dracula #" + str(i), email=f"spooky{i}@hallow.org", content=TextLorem(srange=(4, 12)).sentence(), posted=timezone.now()).save()

    post3 = Blog(title=titleList[2], author=authorList[2], content=contentList[2], posted=timezone.now())
    post3.save()

    for i in range(4):
        Comment(blog=post3, commenter="Dracula #" + str(i), email=f"spooky{i}@hallow.org", content=TextLorem(srange=(4, 12)).sentence(), posted=timezone.now()).save()

    post4 = Blog(title=titleList[3], author=authorList[3], content=contentList[3], posted=timezone.now())
    post4.save()

    for i in range(4):
        Comment(blog=post4, commenter="Dracula #" + str(i), email=f"spooky{i}@hallow.org", content=TextLorem(srange=(4, 12)).sentence(), posted=timezone.now()).save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
